---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  general:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup s5cmd
        uses: peak/action-setup-s5cmd@main
        with:
          version: v2.0.0

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Install assets
        run: npm install --ci

      - name: Build website
        run: hugo --cleanDestinationDir --enableGitInfo --minify --gc

      - name: Upload website
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENDPOINT_URL: https://fsn1.your-objectstorage.com
        run: |
          s5cmd sync --delete public/ s3://cloudhippie-website/

...
