---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  general:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup s5cmd
        uses: peak/action-setup-s5cmd@main
        with:
          version: v2.0.0

      - name: Setup nodejs
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: lts/*
          cache: npm

      - name: Setup hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: latest
          extended: true

      - name: Install assets
        run: npm install --ci

      - name: Build website
        run: hugo --cleanDestinationDir --enableGitInfo --minify --gc

      - name: Upload website
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENDPOINT_URL: https://fsn1.your-objectstorage.com
        run: |
          s5cmd sync --delete public/ s3://cloudhippie-shared-website/

...
